/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dentalpractice.prototype;


import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author wakey
 */
public class AddEditDeletePatientUI extends javax.swing.JFrame {
String FILENAME = "Patients.txt";
String[] savedData;

    /**
     * Creates new form AddEditDeletePatient
     */
    public AddEditDeletePatientUI() {
        initComponents();
        setLocationRelativeTo(null);  // places the form in the center of the screen.
        PatientTable.setAutoCreateRowSorter(true);  // can sort the fields automatically on pressing the top of the jtable(the sort function works to).
        
    }
    DefaultTableModel model;
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PatientTable = new javax.swing.JTable();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        GenderBtn1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        GenderBtn2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        clearBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PatientIDTxt = new javax.swing.JTextField();
        firstNameTxt = new javax.swing.JTextField();
        surnameTxt = new javax.swing.JTextField();
        address1Txt = new javax.swing.JTextField();
        address2Txt = new javax.swing.JTextField();
        DOBTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TelephoneTxt = new javax.swing.JTextField();
        BackBtn = new javax.swing.JButton();
        SearchBtn = new javax.swing.JButton();
        SearchTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        PostCodeTxt = new javax.swing.JTextField();
        DisabilityBtn1 = new javax.swing.JRadioButton();
        DisabilityBtn2 = new javax.swing.JRadioButton();
        SortBtn = new javax.swing.JButton();
        OrderCMB = new javax.swing.JComboBox<>();
        MedHistoryBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        PatientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PatientID", "FirstName", "Surname", "Address1", "Address2", "DOB", "Postcode ", "TeleNumber", "Disability ", "Gender"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        PatientTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatientTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PatientTable);

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jLabel9.setText("Gender");

        jLabel1.setText("PatientID");

        GenderBtn1.setText("Male");
        GenderBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderBtn1ActionPerformed(evt);
            }
        });

        jLabel2.setText("FirstName");

        GenderBtn2.setText("Female");
        GenderBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderBtn2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Surname");

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("address1");

        jLabel5.setText("address2");

        jLabel6.setText("TeleNum");

        address1Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address1TxtActionPerformed(evt);
            }
        });

        jLabel7.setText("DOB");

        jLabel8.setText("Disablilty ");

        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        jLabel10.setText("Postcode");

        DisabilityBtn1.setText("Yes");
        DisabilityBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisabilityBtn1ActionPerformed(evt);
            }
        });

        DisabilityBtn2.setText("No");
        DisabilityBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisabilityBtn2ActionPerformed(evt);
            }
        });

        SortBtn.setText("Sort");
        SortBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortBtnActionPerformed(evt);
            }
        });

        OrderCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ascedning", "descedning" }));

        MedHistoryBtn.setText("PatientsMedHistory");
        MedHistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedHistoryBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBtn)
                        .addGap(161, 161, 161)
                        .addComponent(SearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SearchBtn)
                        .addGap(212, 212, 212)
                        .addComponent(SortBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clearBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MedHistoryBtn)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(BackBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(OrderCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel8))
                                                .addGap(6, 6, 6))
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel3)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel5)
                                                            .addComponent(jLabel4)))
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jLabel1)))
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel7)))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(address1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DOBTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PostCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TelephoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DisabilityBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DisabilityBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(surnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PatientIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(address2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GenderBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GenderBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PatientIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(firstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(surnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(address1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(address2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DOBTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(69, 101, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PostCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(76, 76, 76)
                                .addComponent(TelephoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(DisabilityBtn1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DisabilityBtn2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(GenderBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GenderBtn2)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(38, 38, 38)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBtn)
                            .addComponent(editBtn)
                            .addComponent(deleteBtn)
                            .addComponent(SearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchBtn)
                            .addComponent(SortBtn)
                            .addComponent(OrderCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearBtn)
                            .addComponent(MedHistoryBtn))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BackBtn)
                        .addGap(19, 19, 19))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        model = (DefaultTableModel) PatientTable.getModel();
        String splitBy = ",";
        
        
        String gender = "";
        String id = PatientIDTxt.getText();
        String firstname = firstNameTxt.getText();
        String surname = surnameTxt.getText();
        if(GenderBtn1.isSelected()){
            gender = "Male";
        }else if(GenderBtn2.isSelected()){
            gender = "Female";
        }
        String address1 = address1Txt.getText();
        String address2 = address2Txt.getText();
        String teleNum = TelephoneTxt.getText();
        String dob = DOBTxt.getText();
        String disability ="";
        if(DisabilityBtn1.isSelected()){
            disability = "Yes";
        }else if(DisabilityBtn2.isSelected()){
            disability = "No";
        }
        String postcode = PostCodeTxt.getText();
        
        

       
        boolean validated= true;
        if(firstname.isEmpty() || surname.isEmpty() || gender.isEmpty() || address1.isEmpty() || 
            teleNum.isEmpty() || dob.isEmpty() || disability.isEmpty() || postcode.isEmpty()) {
            JOptionPane.showMessageDialog(null, "One or more fields are Empty, enter the missing fields");
            validated = false;
            
        }else {
            JOptionPane.showMessageDialog(null, "All fields have been entered");
        }
       Validation valObject = new Validation(); 
      
        if (valObject.isInt(id)== false){
            validated = false;
            JOptionPane.showMessageDialog(null, "ID is not an integer");
        }
        if (valObject.isRange(Integer.parseInt(id))== false){
            validated = false;
            JOptionPane.showMessageDialog(null, "ID is not in correct range ,choose between 0 and 10000");
        }
        if (valObject.isPresent(id)== false){
            validated = false;                                         
            JOptionPane.showMessageDialog(null, "ID is not present");
        }
        if (valObject.isLength(teleNum)== false){
            validated = false;
            JOptionPane.showMessageDialog(null, "telephone mumber must be invalid, try again");
        }
       // if (valObject.isDate(dob)== false){
         //   validated = false;
         //   JOptionPane.showMessageDialog(null, "Incorrect date format");
       // }
        if(valObject.RealDate(dob) == false){
            validated = false;
            JOptionPane.showMessageDialog(null, "Not a real date");
        }
        try {
            if (validated == true){
                FileWriter writer = new FileWriter(FILENAME, true);
                writer.write("\n" + id + splitBy + firstname + splitBy + surname + splitBy + address1 + splitBy
                    + address2 + splitBy + dob + splitBy + postcode + splitBy + teleNum + splitBy + disability + splitBy + gender);
                writer.close();
                JOptionPane.showMessageDialog(null, "Success, details are stored in " + FILENAME);
                model.addRow(new Object[] {id,firstname,surname,address1, address2,dob, postcode,teleNum,disability,gender});
            }
            
              
        } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error with" + FILENAME);

            }
    }//GEN-LAST:event_addBtnActionPerformed
    
    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        String editid = PatientIDTxt.getText();
        String firstname = firstNameTxt.getText();
        String surname = surnameTxt.getText();
         String gender = "";
        if(GenderBtn1.isSelected()){
            gender = "Male";
        }else if(GenderBtn2.isSelected()){
            gender = "Female";
        }
        String address1 = address1Txt.getText();
        String address2 = address2Txt.getText();
        String teleNum = TelephoneTxt.getText();
        String dob = DOBTxt.getText();
         String disability = "";
        if(DisabilityBtn1.isSelected()){
            disability = "Yes";
        }else if(DisabilityBtn2.isSelected()){
            disability = "No";
        }
        String postcode = PostCodeTxt.getText();
        
        
        
        String temp = "temp.txt";
        boolean deleted = false;
        boolean renamed = false; 
        File oldFile = new File(FILENAME);
        File newFile = new File(temp);
        String line; // Stores the current line that is being read
        String splitBy = ",";
       
        try{
            FileReader fr = new FileReader(oldFile);
            BufferedReader br = new BufferedReader(fr);
            FileWriter fw = new FileWriter(newFile, true);
            BufferedWriter bw = new BufferedWriter(fw);
            
           
            while((line = br.readLine()) != null) {//runs until end of file (no lines left to read)
                savedData = line.split(","); //saved data is global array and therefore splits each element of that array using the ","
                
                if(savedData[0].equalsIgnoreCase(editid)){ // if id is located in database and matches the id Field
                  
                bw.write(editid + splitBy + firstname + splitBy + surname + splitBy + address1 + splitBy
                    + address2 + splitBy + dob + splitBy + postcode + splitBy + teleNum + splitBy + disability + splitBy + gender);  
                }else{
                   
                JOptionPane.showMessageDialog(null, "No PatientsID was found with this Number please try again");
                }
                
          }  
         bw.flush();
         bw.close(); 
         br.close();
        
         System.gc();
         
         deleted = oldFile.delete();
         renamed = newFile.renameTo(oldFile);
         
         if(renamed){
             JOptionPane.showMessageDialog(null, "Edited users details" + FILENAME);
             renamed = true;
         }else{
             System.err.println("Error with renaming text file");
         }
           
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Error with" + FILENAME);
        System.out.println(e);
        } 
        
        
        int selectedRow = PatientTable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) PatientTable.getModel();
        if( PatientTable.getSelectedRow()==-1){
            if( PatientTable.getSelectedRow()==0){
                JOptionPane.showMessageDialog(null,"Table is empty");
            }else{
                JOptionPane.showMessageDialog(null,"cannot edit table");
            }
        }
        model.setValueAt(PatientIDTxt.getText(), PatientTable.getSelectedRow(),0);
        model.setValueAt(firstNameTxt.getText(), PatientTable.getSelectedRow(),1);
        model.setValueAt(surnameTxt.getText(), PatientTable.getSelectedRow(),2);
        model.setValueAt(address1Txt.getText(), PatientTable.getSelectedRow(),3);
        model.setValueAt(address2Txt.getText(), PatientTable.getSelectedRow(),4);
        model.setValueAt(DOBTxt.getText(), PatientTable.getSelectedRow(),5);
        model.setValueAt(PostCodeTxt.getText(), PatientTable.getSelectedRow(),6);
        model.setValueAt(TelephoneTxt.getText(), PatientTable.getSelectedRow(),7);
        model.setValueAt(disability, PatientTable.getSelectedRow(),8);
        model.setValueAt(gender, PatientTable.getSelectedRow(),9);
        
    }//GEN-LAST:event_editBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        
        String deleteid = PatientIDTxt.getText();
        String temp = "temp.txt";
        File oldFile = new File(FILENAME);
        File newFile = new File(temp);
        String line;
        boolean renamed = false;
        boolean deleted = false;
        try{
            FileReader fr = new FileReader(oldFile);
            BufferedReader br = new BufferedReader(fr);
            FileWriter fw = new FileWriter(newFile, true);
            BufferedWriter bw = new BufferedWriter(fw);
            
           
            while(((line = br.readLine()) != null)) {
                savedData = line.split(",");
                if((savedData[0].equals(deleteid))){
                    
                    
                }else{
                    bw.write(line+"\n");
                }
          }  
         bw.flush();
         bw.close(); 
         br.close();
        
         System.gc();
         
         deleted = oldFile.delete();
         renamed = newFile.renameTo(oldFile);
         
        if(renamed){
             JOptionPane.showMessageDialog(null, "Deleted from user file " + FILENAME);
         }else{
             System.err.println("Error with deleting record from text file");
        }
           
       
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Error with" + FILENAME);
        System.out.println(e);
        } 
        
        int getSelectedRowForDeletetion =  PatientTable.getSelectedRow();
        //check is there is a row selected
        if (getSelectedRowForDeletetion >= 0){
            model.removeRow(getSelectedRowForDeletetion);
            JOptionPane.showMessageDialog(null,"Row deleted");
        }else {
            JOptionPane.showMessageDialog(null, "Unable to Delete");
        }
        
        
        
        
        
        
    }//GEN-LAST:event_deleteBtnActionPerformed
    
    private void GenderBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderBtn1ActionPerformed
    if(GenderBtn1.isSelected());
          GenderBtn2.setSelected(false);     
    }//GEN-LAST:event_GenderBtn1ActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        ClearFields(); /// calls the subroutine to clear all fields (apart from genders radio buttons)
        
    }//GEN-LAST:event_clearBtnActionPerformed

    private void address1TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address1TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address1TxtActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
    SearchTable();     
        //String SearchVal = SearchTxt.getText();
        //Search search = new Search();
        
       // Search.binarySearch(FILENAME,SearchVal);
        //Details(savedData);
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        try {
            FileReader fr = new FileReader(FILENAME);
            BufferedReader br = new BufferedReader(fr);
            
            DefaultTableModel model = (DefaultTableModel)PatientTable.getModel();
            Object[] lines = br.lines().toArray();
            
            for(int i = 0; i < lines.length; i++){
                String[] row = lines[i].toString().split(",");
                model.addRow(row);
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AddEditDeletePatientUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
                                            

    }//GEN-LAST:event_formWindowOpened

    private void PatientTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientTableMouseClicked
        model = (DefaultTableModel) PatientTable.getModel();
        int selectedRow = PatientTable.getSelectedRow();
        
        PatientIDTxt.setText(model.getValueAt(selectedRow, 0).toString());
        firstNameTxt.setText(model.getValueAt(selectedRow, 1).toString());
        surnameTxt.setText(model.getValueAt(selectedRow, 2).toString());
        address1Txt.setText(model.getValueAt(selectedRow, 3).toString());
        address2Txt.setText(model.getValueAt(selectedRow, 4).toString());
        DOBTxt.setText(model.getValueAt(selectedRow, 5).toString());
        PostCodeTxt.setText(model.getValueAt(selectedRow,6).toString());
        TelephoneTxt.setText(model.getValueAt(selectedRow, 7).toString());
        
        String tableDisability = (model.getValueAt(selectedRow, 8).toString());
        switch(tableDisability){
            case "Yes":
            DisabilityBtn1.setSelected(true);
            DisabilityBtn2.setSelected(false);
            
            break;
            case "No":
            DisabilityBtn1.setSelected(false);
            DisabilityBtn2.setSelected(true);
            break;
        }
        String tableGender = model.getValueAt(selectedRow, 9).toString();
       switch(tableGender){
            case "Male":
            GenderBtn1.setSelected(true);
            GenderBtn2.setSelected(false);
            break;
            case "Female":
            GenderBtn1.setSelected(false);
            GenderBtn2.setSelected(true);
            break;
       }                        
    }//GEN-LAST:event_PatientTableMouseClicked

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        MainMenuUI menu = new MainMenuUI();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void GenderBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderBtn2ActionPerformed
        if(GenderBtn2.isSelected());
          GenderBtn1.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_GenderBtn2ActionPerformed

    private void DisabilityBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisabilityBtn1ActionPerformed
        if(DisabilityBtn1.isSelected());
          DisabilityBtn2.setSelected(false); 
    }//GEN-LAST:event_DisabilityBtn1ActionPerformed

    private void DisabilityBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisabilityBtn2ActionPerformed
        if(DisabilityBtn2.isSelected());
          DisabilityBtn1.setSelected(false); 
    }//GEN-LAST:event_DisabilityBtn2ActionPerformed

    private void SortBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortBtnActionPerformed
            FileToArray arrays = new FileToArray();
            
            String[] oneDArray = arrays.fileToOneD(FILENAME);
            String[][] twoDArray = arrays.oneDToTwoD(oneDArray);       
           
            Sort sort = new Sort();
            if(OrderCMB.getSelectedIndex() == 0 ){
            sort.bubbleSort(FILENAME,twoDArray);
            }
            else if(OrderCMB.getSelectedIndex() == 1){
                sort.bubbleSortDescending(FILENAME,twoDArray);
            }
    
            
                
        
    
            
    
    }//GEN-LAST:event_SortBtnActionPerformed

    private void MedHistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedHistoryBtnActionPerformed
  AddMedicalHistoryUI ADH = new AddMedicalHistoryUI();
  ADH.setVisible(true);
    }//GEN-LAST:event_MedHistoryBtnActionPerformed
    private void ClearFields(){
        PatientIDTxt.setText("");
        firstNameTxt.setText("");
        surnameTxt.setText("");
        GenderBtn1.setSelected(false);
        GenderBtn2.setSelected(false);  
        address1Txt.setText("");
        address2Txt.setText("");
        TelephoneTxt.setText("");
        DOBTxt.setText("");
        DisabilityBtn1.setSelected(false);
        DisabilityBtn1.setSelected(false);
        PostCodeTxt.setText("");
    }
    
    


    private void SearchTable(){
        boolean found = false; // boolean flag to indicate if search string found
        String line; // string to temporarily store the line/record read from the file
        try{
        // Create a file reader object 
        FileReader fileReader = new FileReader(FILENAME);
        BufferedReader bufferRead = new BufferedReader(fileReader);
        // Loop through file line by line until the end of the file or until we have found it 
            while (((line = bufferRead.readLine()) != null) && (found == false)) {
                savedData = line.split(",");                                          
                //check if the record matches
                if(savedData[0].equalsIgnoreCase(SearchTxt.getText())){
                    found = true; // set found to true to stop looping 
                }
        }
 
        if (found == true){  
            Details(savedData);//display data in the correct text fields 
            
           
            
        
        }else{
            JOptionPane.showMessageDialog(null, "couldnt find", "Search", JOptionPane.INFORMATION_MESSAGE);
        }
        fileReader.close();  // close file 
        }catch(IOException ex){
            System.err.println("error");
        }
    }
     private void Details(String[] dataArray){ 
        
        PatientIDTxt.setText(dataArray[0]);        //outputing the searched details into the correct details
        firstNameTxt.setText(dataArray[1]);    
        surnameTxt.setText(dataArray[2]);  
        address1Txt.setText(dataArray[3]);
        address2Txt.setText(dataArray[4]);
        DOBTxt.setText(dataArray[5]);
        PostCodeTxt.setText(dataArray[6]);
        TelephoneTxt.setText(dataArray[7]);
        String disability = savedData[8];
        switch(disability){
            case "Yes":
            DisabilityBtn1.setSelected(true);
            DisabilityBtn2.setSelected(false);
            
            break;
            case "No":
            DisabilityBtn1.setSelected(false);
            DisabilityBtn2.setSelected(true);
            break;
        }
       String Gender = savedData[9];
        switch(Gender){
            case "Male":
            GenderBtn1.setSelected(true);
            GenderBtn2.setSelected(false);
            
            break;
            case "Female":
            GenderBtn2.setSelected(false);
            GenderBtn1.setSelected(true);
            break;
        
     }   
     }
 
        

     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEditDeletePatientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEditDeletePatientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEditDeletePatientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEditDeletePatientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEditDeletePatientUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JTextField DOBTxt;
    private javax.swing.JRadioButton DisabilityBtn1;
    private javax.swing.JRadioButton DisabilityBtn2;
    private javax.swing.JRadioButton GenderBtn1;
    private javax.swing.JRadioButton GenderBtn2;
    private javax.swing.JButton MedHistoryBtn;
    private javax.swing.JComboBox<String> OrderCMB;
    private javax.swing.JTextField PatientIDTxt;
    private javax.swing.JTable PatientTable;
    private javax.swing.JTextField PostCodeTxt;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField SearchTxt;
    private javax.swing.JButton SortBtn;
    private javax.swing.JTextField TelephoneTxt;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField address1Txt;
    private javax.swing.JTextField address2Txt;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JTextField firstNameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField surnameTxt;
    // End of variables declaration//GEN-END:variables
}
