/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dentalpractice.prototype;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wake5
 */
public class AddEditDeleteTreatmentUI extends javax.swing.JFrame {
String FILENAME = "Treatment.Txt";
String[] savedData;
    /**
     * Creates new form AddEditDeleteTreatment
     */
    public AddEditDeleteTreatmentUI() {
        initComponents();
        setLocationRelativeTo(null);
    }
    DefaultTableModel model;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TreatmentIDTxt = new javax.swing.JTextField();
        TreatmentTypeTxt = new javax.swing.JTextField();
        TreatmentCostTxt = new javax.swing.JTextField();
        MaterialsTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TreatmentTableTbl = new javax.swing.JTable();
        HBPBtn = new javax.swing.JRadioButton();
        HeartMurmurBtn = new javax.swing.JRadioButton();
        EmpysemaBtn = new javax.swing.JRadioButton();
        SmokerBtn = new javax.swing.JRadioButton();
        CFBtn = new javax.swing.JRadioButton();
        HepatitisBBtn = new javax.swing.JRadioButton();
        HIVBtn = new javax.swing.JRadioButton();
        HaemophiliaBtn = new javax.swing.JRadioButton();
        DiabetesBtn = new javax.swing.JRadioButton();
        CancerBtn = new javax.swing.JRadioButton();
        HiatusHerniaBtn = new javax.swing.JRadioButton();
        LiverDiseaseBtn = new javax.swing.JRadioButton();
        PencillinBtn = new javax.swing.JRadioButton();
        HayFeverBtn = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        AsthmaBtn = new javax.swing.JRadioButton();
        PregnantBtn = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        AddBtn = new javax.swing.JButton();
        EditBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        OtherTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("TreatmentID");

        jLabel3.setText("Treatment Cost");

        jLabel2.setText("Treatment Type");

        jLabel4.setText("Materials required");

        jLabel5.setText("Dont give treatment to patients that have ");

        jLabel6.setText("these medical health problems");

        TreatmentCostTxt.setText("    ");

        MaterialsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaterialsTxtActionPerformed(evt);
            }
        });

        TreatmentTableTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TreatmentID", "TreatmentType", "TreatmentCost", "MaterialsRequired", "Health Problems with medical history", "Other health Problems"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TreatmentTableTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TreatmentTableTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TreatmentTableTbl);
        if (TreatmentTableTbl.getColumnModel().getColumnCount() > 0) {
            TreatmentTableTbl.getColumnModel().getColumn(0).setMinWidth(80);
            TreatmentTableTbl.getColumnModel().getColumn(0).setMaxWidth(80);
            TreatmentTableTbl.getColumnModel().getColumn(1).setResizable(false);
            TreatmentTableTbl.getColumnModel().getColumn(2).setMinWidth(100);
            TreatmentTableTbl.getColumnModel().getColumn(2).setMaxWidth(100);
            TreatmentTableTbl.getColumnModel().getColumn(4).setResizable(false);
        }

        HBPBtn.setText("HighBloodPresure");

        HeartMurmurBtn.setText("HeartMurmur");

        EmpysemaBtn.setText("Emphysema");
        EmpysemaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpysemaBtnActionPerformed(evt);
            }
        });

        SmokerBtn.setText("Smoker");

        CFBtn.setText("CysticFibrosis");

        HepatitisBBtn.setText("Hepatitis B");

        HIVBtn.setText("H.I.V");

        HaemophiliaBtn.setText("Haemophilia");

        DiabetesBtn.setText("Diabetes");

        CancerBtn.setText("Cancer");

        HiatusHerniaBtn.setText("Hiatus Hernia");

        LiverDiseaseBtn.setText("LiverDisease");

        PencillinBtn.setText("Pencillin");

        HayFeverBtn.setText("HayFever");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Add Edit and Delete any Treatment");

        AsthmaBtn.setText("Asthma");

        PregnantBtn.setText("Pregnant");
        PregnantBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PregnantBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Other");
        jLabel8.setToolTipText("");

        AddBtn.setText("Add");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        EditBtn.setText("Edit");
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        jButton4.setText("Search");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascending", "Descending" }));

        jButton5.setText("Sort");

        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Type" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addComponent(TreatmentIDTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(15, 15, 15)
                                    .addComponent(TreatmentTypeTxt))
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(TreatmentCostTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(AsthmaBtn)
                                            .addGap(48, 48, 48))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(HBPBtn)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PregnantBtn)
                                        .addComponent(LiverDiseaseBtn)
                                        .addComponent(CancerBtn)
                                        .addComponent(HaemophiliaBtn)
                                        .addComponent(HepatitisBBtn)
                                        .addComponent(SmokerBtn)
                                        .addComponent(HeartMurmurBtn)
                                        .addComponent(HayFeverBtn)))
                                .addComponent(EmpysemaBtn)
                                .addComponent(CFBtn)
                                .addComponent(HIVBtn)
                                .addComponent(DiabetesBtn)
                                .addComponent(PencillinBtn)
                                .addComponent(HiatusHerniaBtn)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(OtherTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MaterialsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteBtn)
                        .addGap(27, 27, 27)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(50, 50, 50)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(0, 136, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BackBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AddBtn)
                                    .addComponent(EditBtn)
                                    .addComponent(DeleteBtn)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton4)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton5)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TreatmentIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TreatmentTypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TreatmentCostTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(MaterialsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HBPBtn)
                            .addComponent(HeartMurmurBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmpysemaBtn)
                            .addComponent(SmokerBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CFBtn)
                            .addComponent(HepatitisBBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HIVBtn)
                            .addComponent(HaemophiliaBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DiabetesBtn)
                            .addComponent(CancerBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HiatusHerniaBtn)
                            .addComponent(LiverDiseaseBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PencillinBtn)
                            .addComponent(HayFeverBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AsthmaBtn)
                            .addComponent(PregnantBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(OtherTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BackBtn)
                        .addGap(11, 11, 11))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MaterialsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaterialsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaterialsTxtActionPerformed

    private void TreatmentTableTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TreatmentTableTblMouseClicked
    model = (DefaultTableModel) TreatmentTableTbl.getModel();
        int selectedRow = TreatmentTableTbl.getSelectedRow();
        
        TreatmentIDTxt.setText(model.getValueAt(selectedRow, 0).toString());
        TreatmentTypeTxt.setText(model.getValueAt(selectedRow, 1).toString());
        TreatmentCostTxt.setText(model.getValueAt(selectedRow, 2).toString());
        MaterialsTxt.setText(model.getValueAt(selectedRow, 3).toString());
        
        String medHealth = (model.getValueAt(selectedRow, 4).toString());
        if(medHealth == "HighBloodPressure"){
          HBPBtn.setSelected(true);   
        }else if(medHealth.equals("HeartMurmur")){
            HeartMurmurBtn.setSelected(true);
            }else if(medHealth.equals("Emphysema")){
            EmpysemaBtn.setSelected(true);
            }else if(medHealth.equals("Smoker")){
            SmokerBtn.setSelected(true);
            }else if(medHealth.equals("CysticFibrosis")){
            CFBtn.setSelected(true);
            }else if(medHealth.equals("HepatitisB")){
            HepatitisBBtn.setSelected(true);
            }else if(medHealth.equals("Diabetes")){
            DiabetesBtn.setSelected(true);
            }else if(medHealth.equals("Cancer")){
            CancerBtn.setSelected(true);
            }else if(medHealth.equals( "HiatusHernia")){
            HiatusHerniaBtn.setSelected(true);
            }else if(medHealth.equals("LiverDisease")){
            LiverDiseaseBtn.setSelected(true);
            }else if(medHealth.equals("Pencillin")){
            PencillinBtn.setSelected(true);
            }else if(medHealth .equals("HayFevern")){
            HayFeverBtn.setSelected(true);
            }else if(medHealth.equals( "Asthma")){
            AsthmaBtn.setSelected(true);
            }else if(medHealth.equals("Pregnant")){
            PregnantBtn.setSelected(true);
            }else if(medHealth.equals("H.I.V")){
            HIVBtn.setSelected(true);
            }
      OtherTxt.setText(model.getValueAt(selectedRow, 5).toString());      
    }//GEN-LAST:event_TreatmentTableTblMouseClicked

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        MainMenuUI menu = new MainMenuUI();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        model = (DefaultTableModel) TreatmentTableTbl.getModel();
        String splitBy = ",";
        String medHealth = "";
        String id = TreatmentIDTxt.getText();
        String Ttype = TreatmentTypeTxt.getText();
        String Tcost = TreatmentCostTxt.getText();
        String Materials = MaterialsTxt.getText();
        if(HBPBtn.isSelected()){
        medHealth = "HighBloodPressure";
        }else if(HeartMurmurBtn.isSelected()){
            medHealth = "HeartMurmur";
        }
        else if(EmpysemaBtn.isSelected()){
            medHealth = "Emphysema";
        }else if(SmokerBtn.isSelected()){
            medHealth = "Smoker";
        }else if(CFBtn.isSelected()){
            medHealth = "CysticFibrosis";
        }else if(HepatitisBBtn.isSelected()){
            medHealth = "HepatitisB";
        }else if(HIVBtn.isSelected()){
            medHealth = "H.I.V";
        }else if(HaemophiliaBtn.isSelected()){
            medHealth = "Haemophilia";
        }else if(DiabetesBtn.isSelected()){
            medHealth = "Diabetes";
        }else if(CancerBtn.isSelected()){
            medHealth = "Cancer";
        }else if(HiatusHerniaBtn.isSelected()){
            medHealth = "HiatusHernia";
        }else if(LiverDiseaseBtn.isSelected()){
            medHealth = "LiverDisease";
        }else if(PencillinBtn.isSelected()){
            medHealth = "Pencillin";
        }else if(HayFeverBtn.isSelected()){
            medHealth = "HayFever";
        }else if(AsthmaBtn.isSelected()){
            medHealth = "Asthma";
        }else if(PregnantBtn.isSelected()){
            medHealth = "Pregnant";  
        }
        String other = OtherTxt.getText();
        
        boolean vaildated = true;
        try {
            if (vaildated == true){
                FileWriter writer = new FileWriter(FILENAME, true);
                writer.write("\n" + id + splitBy + Ttype + splitBy + Tcost + splitBy + Materials + splitBy + medHealth +splitBy+ other);
                writer.close();
                JOptionPane.showMessageDialog(null, "Success, details are stored in " + FILENAME);
                model.addRow(new Object[] {id,Ttype,Tcost,Materials,medHealth,other});
            }
            
              
        } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error with" + FILENAME);

            }
            
    }//GEN-LAST:event_AddBtnActionPerformed

    private void PregnantBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PregnantBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PregnantBtnActionPerformed

    private void EmpysemaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpysemaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpysemaBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            FileReader fr = new FileReader(FILENAME);
            BufferedReader br = new BufferedReader(fr);
            
            DefaultTableModel model = (DefaultTableModel)TreatmentTableTbl.getModel();
            Object[] lines = br.lines().toArray();
            
            for(int i = 0; i < lines.length; i++){
                String[] row = lines[i].toString().split(",");
                model.addRow(row);
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AddEditDeleteTreatmentUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_formWindowOpened

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
         String deleteid = TreatmentIDTxt.getText();
        String temp = "temp.txt";
        File oldFile = new File(FILENAME);
        File newFile = new File(temp);
        String line;
        boolean renamed = false;
        boolean deleted = false;
        try{
            FileReader fr = new FileReader(oldFile);
            BufferedReader br = new BufferedReader(fr);
            FileWriter fw = new FileWriter(newFile, true);
            BufferedWriter bw = new BufferedWriter(fw);
            
           
            while(((line = br.readLine()) != null)) {
                savedData = line.split(",");
                if((savedData[0].equals(deleteid))){
                    
                    
                }else{
                    bw.write(line+"\n");
                }
          }  
         bw.flush();
         bw.close(); 
         br.close();
        
         System.gc();
         
         deleted = oldFile.delete();
         renamed = newFile.renameTo(oldFile);
         
         if(renamed){
             JOptionPane.showMessageDialog(null, "Deleted from Treatment file " + FILENAME);
         }else{
             System.err.println("Error with deleting record from text file");
         }
           
       
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Error with" + FILENAME);
        System.out.println(e);
        } 
        
        int getSelectedRowForDeletetion =  TreatmentTableTbl.getSelectedRow();
        //check is there is a row selected
        if (getSelectedRowForDeletetion >= 0){
            model.removeRow(getSelectedRowForDeletetion);
            JOptionPane.showMessageDialog(null,"Row deleted");
        }else {
            JOptionPane.showMessageDialog(null, "Unable to Delete");
        }
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
       model = (DefaultTableModel) TreatmentTableTbl.getModel();
        String splitBy = ",";
        String medHealth = "";
        String id = TreatmentIDTxt.getText();
        String Ttype = TreatmentTypeTxt.getText();
        String Tcost = TreatmentCostTxt.getText();
        String Materials = MaterialsTxt.getText();
        if(HBPBtn.isSelected()){
        medHealth = "HighBloodPressure";
        }else if(HeartMurmurBtn.isSelected()){
            medHealth = "HeartMurMur";
        }
        else if(EmpysemaBtn.isSelected()){
            medHealth = "Emphysema";
        }else if(SmokerBtn.isSelected()){
            medHealth = "Smoker";
        }else if(CFBtn.isSelected()){
            medHealth = "CysticFibrosis";
        }else if(HepatitisBBtn.isSelected()){
            medHealth = "HepatitisB";
        }else if(HIVBtn.isSelected()){
            medHealth = "H.I.V";
        }else if(HaemophiliaBtn.isSelected()){
            medHealth = "Haemophilia";
        }else if(DiabetesBtn.isSelected()){
            medHealth = "Diabetes";
        }else if(CancerBtn.isSelected()){
            medHealth = "Cancer";
        }else if(HiatusHerniaBtn.isSelected()){
            medHealth = "HiatusHernia";
        }else if(LiverDiseaseBtn.isSelected()){
            medHealth = "LiverDisease";
        }else if(PencillinBtn.isSelected()){
            medHealth = "Pencillin";
        }else if(HayFeverBtn.isSelected()){
            medHealth = "HayFevern";
        }else if(AsthmaBtn.isSelected()){
            medHealth = "Asthma";
        }else if(PregnantBtn.isSelected()){
            medHealth = "Pregnant";  
        }
        String other = OtherTxt.getText(); 
        
        
        
        DefaultTableModel model = (DefaultTableModel) TreatmentTableTbl.getModel();
        if( TreatmentTableTbl.getSelectedRow()==-1){
            if( TreatmentTableTbl.getSelectedRow()==0){
                JOptionPane.showMessageDialog(null,"Table is empty");
            }else{
                JOptionPane.showMessageDialog(null,"cannot edit table");
            }
        }
        model.setValueAt(id,TreatmentTableTbl.getSelectedRow(),0);
        model.setValueAt(Ttype, TreatmentTableTbl.getSelectedRow(),1);
        model.setValueAt(Tcost, TreatmentTableTbl.getSelectedRow(),2);
        model.setValueAt(Materials, TreatmentTableTbl.getSelectedRow(),3);
        model.setValueAt(HBPBtn.getText(), TreatmentTableTbl.getSelectedRow(),4);
        model.setValueAt(HeartMurmurBtn.getText(), TreatmentTableTbl.getSelectedRow(),4);
        model.setValueAt(EmpysemaBtn.getText(), TreatmentTableTbl.getSelectedRow(),4);
        model.setValueAt(SmokerBtn.getText(), TreatmentTableTbl.getSelectedRow(),4);
        model.setValueAt(CFBtn.getText(), TreatmentTableTbl.getSelectedRow(),4);
        model.setValueAt(HepatitisBBtn.getText(), TreatmentTableTbl.getSelectedRow(),4);
        model.setValueAt(HIVBtn.getText(), TreatmentTableTbl.getSelectedRow(),4);
        model.setValueAt(HaemophiliaBtn.getText(), TreatmentTableTbl.getSelectedRow(),4);
        model.setValueAt(DiabetesBtn.getText(), TreatmentTableTbl.getSelectedRow(),4);
        model.setValueAt(CancerBtn.getText(), TreatmentTableTbl.getSelectedRow(),4);
        model.setValueAt(HiatusHerniaBtn.getText(), TreatmentTableTbl.getSelectedRow(),4);
        model.setValueAt(PencillinBtn.getText(), TreatmentTableTbl.getSelectedRow(),4);
        model.setValueAt(LiverDiseaseBtn.getText(), TreatmentTableTbl.getSelectedRow(),4);
        model.setValueAt(HayFeverBtn.getText(), TreatmentTableTbl.getSelectedRow(),4);
        model.setValueAt(AsthmaBtn.getText(), TreatmentTableTbl.getSelectedRow(),4);
        model.setValueAt(PregnantBtn.getText(), TreatmentTableTbl.getSelectedRow(),4);
        model.setValueAt(other, TreatmentTableTbl.getSelectedRow(),5);
        
        
    }//GEN-LAST:event_EditBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEditDeleteTreatmentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEditDeleteTreatmentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEditDeleteTreatmentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEditDeleteTreatmentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEditDeleteTreatmentUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JRadioButton AsthmaBtn;
    private javax.swing.JButton BackBtn;
    private javax.swing.JRadioButton CFBtn;
    private javax.swing.JRadioButton CancerBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JRadioButton DiabetesBtn;
    private javax.swing.JButton EditBtn;
    private javax.swing.JRadioButton EmpysemaBtn;
    private javax.swing.JRadioButton HBPBtn;
    private javax.swing.JRadioButton HIVBtn;
    private javax.swing.JRadioButton HaemophiliaBtn;
    private javax.swing.JRadioButton HayFeverBtn;
    private javax.swing.JRadioButton HeartMurmurBtn;
    private javax.swing.JRadioButton HepatitisBBtn;
    private javax.swing.JRadioButton HiatusHerniaBtn;
    private javax.swing.JRadioButton LiverDiseaseBtn;
    private javax.swing.JTextField MaterialsTxt;
    private javax.swing.JTextField OtherTxt;
    private javax.swing.JRadioButton PencillinBtn;
    private javax.swing.JRadioButton PregnantBtn;
    private javax.swing.JRadioButton SmokerBtn;
    private javax.swing.JTextField TreatmentCostTxt;
    private javax.swing.JTextField TreatmentIDTxt;
    private javax.swing.JTable TreatmentTableTbl;
    private javax.swing.JTextField TreatmentTypeTxt;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
