/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dentalpractice.prototype;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
/**
 *
 * @author wake5
 */
public class AppointmentCalandarUI extends javax.swing.JFrame {

    /**
     * Creates new form AppointmentCalandarUI
     */
    public static int realYear, realMonth, realDay, currentYear, currentMonth;
    public static int selectedDate, selectedMonth, selectedYear;
    public AppointmentCalandarUI() {
        initComponents();
    }
    String APPFILENAME = "Appointment.txt";
    String PTFILENAME = "Patients.txt";
    String STFILENAME = "Staff.txt";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BackBtn = new javax.swing.JButton();
        MonthLbl = new javax.swing.JLabel();
        yearCmb = new javax.swing.JComboBox<>();
        btnPrevYear = new javax.swing.JButton();
        btnPrevMonth = new javax.swing.JButton();
        btnNextYear = new javax.swing.JButton();
        btnNextMonth = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CalTbl = new javax.swing.JTable();
        Calandar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        MonthLbl.setText("Month");

        yearCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearCmbActionPerformed(evt);
            }
        });

        btnPrevYear.setText("<<");
        btnPrevYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevYearActionPerformed(evt);
            }
        });

        btnPrevMonth.setText("<");
        btnPrevMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevMonthActionPerformed(evt);
            }
        });

        btnNextYear.setText(">>");
        btnNextYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextYearActionPerformed(evt);
            }
        });

        btnNextMonth.setText(">");
        btnNextMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextMonthActionPerformed(evt);
            }
        });

        CalTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        CalTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalTblcalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CalTbl);

        Calandar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Calandar.setText("Calandar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnPrevYear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btnPrevMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(MonthLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(btnNextMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnNextYear, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BackBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Calandar)
                                .addGap(196, 196, 196)
                                .addComponent(yearCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(yearCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Calandar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BackBtn)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MonthLbl)
                            .addComponent(btnPrevYear)
                            .addComponent(btnPrevMonth)
                            .addComponent(btnNextYear)
                            .addComponent(btnNextMonth))
                        .addGap(20, 20, 20))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        MainMenuUI menu = new MainMenuUI();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        GregorianCalendar gregCal = new GregorianCalendar();
        realDay = gregCal.get(GregorianCalendar.DAY_OF_MONTH);
        realMonth = gregCal.get(GregorianCalendar.MONTH);
        realYear = gregCal.get(GregorianCalendar.YEAR);
        currentMonth = realMonth;
        currentYear = realYear;
        
        System.out.println("realYear="+realYear);
        System.out.println("realMonth="+realMonth);
        
        
        DefaultTableModel model=(DefaultTableModel)CalTbl.getModel();
        String[] headers = {"Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"}; //All headers

        for (int i=0; i<7; i++)
        {
            model.addColumn(headers[i]);
        }
        
        CalTbl.setColumnSelectionAllowed(true);
        CalTbl.setRowSelectionAllowed(true);
        CalTbl.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        CalTbl.setRowHeight(38);
        model.setRowCount(6);
        model.setColumnCount(7);
        
        for (int i=realYear-100; i<=realYear+100; i++)
        {
            yearCmb.addItem(String.valueOf(i));
        }

        refreshCal(realMonth, realYear);
        
         
    }//GEN-LAST:event_formWindowOpened

    private void yearCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearCmbActionPerformed
        currentYear=Integer.parseInt(yearCmb.getSelectedItem().toString());
        refreshCal(currentMonth, currentYear);
    }//GEN-LAST:event_yearCmbActionPerformed

    private void btnPrevYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevYearActionPerformed
        if(currentYear==realYear-100)
        {
            btnPrevYear.setEnabled(false);
        }
        else
        currentYear-=1;
        refreshCal(currentMonth,currentYear);
    }//GEN-LAST:event_btnPrevYearActionPerformed

    private void btnPrevMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevMonthActionPerformed
        if(currentMonth==0)
        {
            currentMonth=11;
            currentYear-=1;
        }
        else
        {
            currentMonth-=1;
        }
        refreshCal(currentMonth, currentYear);
    }//GEN-LAST:event_btnPrevMonthActionPerformed

    private void btnNextYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextYearActionPerformed
        if(currentYear==realYear+100)
        {
            btnNextYear.setEnabled(false);
        }
        else
        currentYear+=1;
        refreshCal(currentMonth,currentYear);
    }//GEN-LAST:event_btnNextYearActionPerformed

    private void btnNextMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextMonthActionPerformed
        if(currentMonth==11)
        {
            currentMonth=0;
            currentYear+=1;
        }
        else
        {
            currentMonth+=1;
        }
        refreshCal(currentMonth, currentYear);
    }//GEN-LAST:event_btnNextMonthActionPerformed

    private void CalTblcalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalTblcalMouseClicked
        int row=CalTbl.rowAtPoint(evt.getPoint());          // Gets the row where the mouse is pointing
        int col= CalTbl.columnAtPoint(evt.getPoint());      // Gets the col where the mouse is pointing

        try
        {
            selectedDate=Integer.parseInt(CalTbl.getValueAt(row, col).toString());
        }
        catch(Exception e)
        {
            selectedDate=0;
            //e.printStackTrace();
        }
        System.out.println("Date: "+selectedDate);
        selectedMonth=getMonth(MonthLbl.getText());
        System.out.println("Month: "+selectedMonth);
        try
        {
            selectedYear=Integer.parseInt(yearCmb.getSelectedItem().toString());
        }
        catch(Exception ex)
        {
            selectedYear=realYear;
        }
        System.out.println("Year: "+selectedYear);
        if(selectedDate>=1 && selectedDate<=31 && selectedMonth>=1 && selectedMonth<=12)
        {
            CalendarOptionsUI CalOpt=new CalendarOptionsUI();
            CalOpt.setVisible(true);
            this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Invalid Date");
        }

    }//GEN-LAST:event_CalTblcalMouseClicked
public void refreshCal(int month, int year)
        {
            String[] months =  {"January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"};
            
            int numOfDays;
            int startOfMonth;
            
            MonthLbl.setText(months[month]);
            yearCmb.setSelectedItem(String.valueOf(year));
            
            btnNextMonth.setEnabled(true);
            btnNextYear.setEnabled(true);
            btnPrevMonth.setEnabled(true);
            btnPrevYear.setEnabled(true);
            if(month==11)
            {
                btnNextMonth.setEnabled(false);
            }
            if(month==0)
            {
                btnPrevMonth.setEnabled(false);
            }
            if(year==realYear-10)
            {
                btnPrevYear.setEnabled(false);
            }
            if(year==realYear+100)
            {
                btnNextYear.setEnabled(false);
            }
            
            //Clearing the previous values in calendar
            for(int i=0;i<6;i++)
            {
                for(int j=0;j<7;j++)
                {
                    CalTbl.setValueAt(null, i, j);    //Setting null value to every cell 
                }
            }
            
            GregorianCalendar calendar = new GregorianCalendar(year, month, 1); //Gives first day of the month
            numOfDays = calendar.getActualMaximum(GregorianCalendar.DAY_OF_MONTH); //Gives total Number of days
            startOfMonth=calendar.get(GregorianCalendar.DAY_OF_WEEK); // Gives the starting day
            System.out.println("startOfMonth = "+startOfMonth);
            System.out.println("numOfDays = "+numOfDays);
            
            
            // Making the new calendar
            
            for(int i=1;i<=numOfDays;i++)
            {
                int row = (i+startOfMonth-2)/7;
                
                int column  =  ((i+startOfMonth)%7-2%7 + 7)%7;                                                  
                
                CalTbl.setValueAt(i, row, column);
                
                CalTbl.setDefaultRenderer(CalTbl.getColumnClass(0), new TableCellRenderer());
            }
        }
 public int getMonth(String month){
            int monthNumber=-1;
            if(month=="January")
            {
                monthNumber=1;
            }
            else if(month=="February")
            {
                monthNumber=2;
            }
            else if(month=="March")
            {
                monthNumber=3;
            }
            else if(month=="April")
            {
                monthNumber=4;
            }
            else if(month=="May")
            {
                monthNumber=5;
            }
            else if(month=="June")
            {
                monthNumber=6;
            }
            else if(month=="July")
            {
                monthNumber=7;
            }
            else if(month=="August")
            {
                monthNumber=8;
            }
            else if(month=="September")
            {
                monthNumber=9;
            }
            else if(month=="October")
            {
                monthNumber=10;
            }
            else if(month=="November")
            {
                monthNumber=11;
            }
            else if(month=="December")
            {
                monthNumber=12;
            }
            return monthNumber;
        }
          
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentCalandarUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentCalandarUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentCalandarUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentCalandarUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppointmentCalandarUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JTable CalTbl;
    private javax.swing.JLabel Calandar;
    private javax.swing.JLabel MonthLbl;
    private javax.swing.JButton btnNextMonth;
    private javax.swing.JButton btnNextYear;
    private javax.swing.JButton btnPrevMonth;
    private javax.swing.JButton btnPrevYear;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> yearCmb;
    // End of variables declaration//GEN-END:variables
}
