/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dentalpractice.prototype;

import javax.swing.JOptionPane;

/**
 *
 * @author wake5
 */
public class CalendarOptionsUI extends javax.swing.JFrame {

    /**
     * Creates new form CalendarOptions
     */
    public CalendarOptionsUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DateLbl = new javax.swing.JLabel();
        ViewAppBtn = new javax.swing.JRadioButton();
        AEDAppBtn = new javax.swing.JRadioButton();
        BackBtn = new javax.swing.JRadioButton();
        MenuBtn = new javax.swing.JRadioButton();
        OkayBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("What would you like to choose");

        DateLbl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        DateLbl.setText("Seleceted Date:");

        ViewAppBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ViewAppBtn.setText("ViewAppointmentDatabase");
        ViewAppBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAppBtnActionPerformed(evt);
            }
        });

        AEDAppBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        AEDAppBtn.setText("Add/Edit/Delete Appointment");
        AEDAppBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AEDAppBtnActionPerformed(evt);
            }
        });

        BackBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        BackBtn.setText("Return back to Calendar");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        MenuBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        MenuBtn.setText("Return To Main Menu");
        MenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBtnActionPerformed(evt);
            }
        });

        OkayBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        OkayBtn.setText("Okay");
        OkayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkayBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ViewAppBtn)
                            .addComponent(AEDAppBtn)
                            .addComponent(BackBtn)
                            .addComponent(MenuBtn)
                            .addComponent(OkayBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DateLbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel1)))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(DateLbl)
                .addGap(56, 56, 56)
                .addComponent(AEDAppBtn)
                .addGap(18, 18, 18)
                .addComponent(ViewAppBtn)
                .addGap(18, 18, 18)
                .addComponent(BackBtn)
                .addGap(32, 32, 32)
                .addComponent(MenuBtn)
                .addGap(50, 50, 50)
                .addComponent(OkayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OkayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkayBtnActionPerformed
        int selectedOption = 0;        //setting an integer for selected option which will be used later in a switch case 
                                        // to perform different operations
        if(AEDAppBtn.isSelected())    //each button will give a different option therefore perform a different operation in the switch case below
           selectedOption=1;
       else if(ViewAppBtn.isSelected())
           selectedOption=2;
       else if(BackBtn.isSelected())
           selectedOption=3;
       else if(MenuBtn.isSelected())
           selectedOption=4;
        
       switch(selectedOption)  // condition defined above , depending on the button that is toggled , will perform either one of these operations 
       {                        // by using the numbers 1,2,3,4
           case 1:
                { 
                    AddEditDeleteAppointmentUI AEDApp=new AddEditDeleteAppointmentUI(); //makes constructor method so that we can use 
                    AEDApp.setVisible(true);  //AddEditDeleteAppointmentUI functions/Methods/objects  in this case we can open the AEDApp form(this is an example of OO progmramming)
                    
                    this.dispose();//removoves the current form from screen and from memory
                break; // end of this case
                }
           case 2: 
                ViewAppointmentDatabaseUI ViewApp = new ViewAppointmentDatabaseUI(); // makes constructor method so that we can use 
                ViewApp.setVisible(true); //ViewAppointUI functions/Methods/objects   in this case we can open the ViewApp form(this is an example of OO progmramming)
                this.dispose(); //removoves the current form from screen and from memory
                break;  // end of this case
           case 3: 
                {
                    AppointmentCalandarUI AppCal = new AppointmentCalandarUI(); // makes constructor method so that we can use 
                    AppCal.setVisible(true);//AppointmentCalandarUI functions/Methods/objects   in this case we can return back to the calendar form(this is an example of OO progmramming)
                    this.dispose(); //removoves the current form from screen and from memory
                    break; // end of this case
                }
              
           case 4: 
                {
                    MainMenuUI mm = new MainMenuUI();// makes constructor method so that we can use 
                    mm.setVisible(true); //MainMenuUI functions/Methods/objects in this case we can return back to the calendar form   (this is an example of OO progmramming)        
                    this.dispose(); //removoves the current form from screen and from memory
                        
                    
                    break; // end of this case
                }
               
           default:JOptionPane.showMessageDialog(null, "Select An option"); // Output message to user Telling them what to do.
       }
    }//GEN-LAST:event_OkayBtnActionPerformed

    private void AEDAppBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AEDAppBtnActionPerformed
         if(AEDAppBtn.isSelected());     //these 4 buttons just stop more than two buttons being selected at one time 
          ViewAppBtn.setSelected(false); //which could prevent the system from crashing as two operations dont occur at once.
          BackBtn.setSelected(false);
          MenuBtn.setSelected(false);
    }//GEN-LAST:event_AEDAppBtnActionPerformed

    private void ViewAppBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAppBtnActionPerformed
        if(ViewAppBtn.isSelected());
          AEDAppBtn.setSelected(false);   
          BackBtn.setSelected(false);
          MenuBtn.setSelected(false);
    }//GEN-LAST:event_ViewAppBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        if(BackBtn.isSelected());
          AEDAppBtn.setSelected(false);   
          ViewAppBtn.setSelected(false);
          MenuBtn.setSelected(false);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void MenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBtnActionPerformed
        if(MenuBtn.isSelected());
          AEDAppBtn.setSelected(false);   
          ViewAppBtn.setSelected(false);
          BackBtn.setSelected(false);
    }//GEN-LAST:event_MenuBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       DateLbl.setText(AppointmentCalandarUI.selectedDate+" - "+AppointmentCalandarUI.selectedMonth+" - "+AppointmentCalandarUI.selectedYear);
       AEDAppBtn.setSelected(true);//the line above = sets the datelbl the real date from when the user clicks on a date from the calendar.
       //this button just makes it so that no button cannot be selected which would therefore prevent the system from crasing.
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalendarOptionsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalendarOptionsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalendarOptionsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalendarOptionsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalendarOptionsUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AEDAppBtn;
    private javax.swing.JRadioButton BackBtn;
    private javax.swing.JLabel DateLbl;
    private javax.swing.JRadioButton MenuBtn;
    private javax.swing.JButton OkayBtn;
    private javax.swing.JRadioButton ViewAppBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
