/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dentalpractice.prototype;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.FileReader;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author wakey
 */
public class MainMenuUI extends javax.swing.JFrame {
String FILENAME =  "Details.txt";
String savedData[];
    /**
     * Creates new form Menu
     */
    public MainMenuUI() {
        initComponents();
        setLocationRelativeTo(null);
        showDate();
        showTime();
        
    }
    public void username(String user){
        UsernameLbl.setText(user);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PatientBtn = new javax.swing.JButton();
        StaffBtn = new javax.swing.JButton();
        AppointmentBtn = new javax.swing.JButton();
        MedicalBtn = new javax.swing.JButton();
        LogoutBtn = new javax.swing.JButton();
        TreatmentBtn = new javax.swing.JButton();
        UsernameLbl = new javax.swing.JLabel();
        DateLbl = new javax.swing.JLabel();
        TimeLbl = new javax.swing.JLabel();
        adminBtn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setName("Menu"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Menu");

        PatientBtn.setText("Patient");
        PatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientBtnActionPerformed(evt);
            }
        });

        StaffBtn.setText("Staff");
        StaffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffBtnActionPerformed(evt);
            }
        });

        AppointmentBtn.setText("Appointments");
        AppointmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppointmentBtnActionPerformed(evt);
            }
        });

        MedicalBtn.setText("MedicalHistory");
        MedicalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicalBtnActionPerformed(evt);
            }
        });

        LogoutBtn.setText("logout");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });

        TreatmentBtn.setText("Treatment");
        TreatmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TreatmentBtnActionPerformed(evt);
            }
        });

        UsernameLbl.setText("username");

        DateLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DateLbl.setText("Date");

        TimeLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TimeLbl.setText("Time");

        adminBtn.setText("Admin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(AppointmentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                        .addComponent(TreatmentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(PatientBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MedicalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StaffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(131, 131, 131))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(UsernameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutBtn)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TimeLbl)
                            .addComponent(DateLbl)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addComponent(DateLbl)
                        .addGap(40, 40, 40)
                        .addComponent(TimeLbl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 152, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PatientBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(AppointmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(StaffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(MedicalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TreatmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsernameLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LogoutBtn, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientBtnActionPerformed
        ViewPatientsDatabaseUI patient = new ViewPatientsDatabaseUI();
        patient.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PatientBtnActionPerformed

    private void StaffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffBtnActionPerformed
         ViewStaffDatabaseUI staff = new ViewStaffDatabaseUI();
         staff.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_StaffBtnActionPerformed

    private void AppointmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppointmentBtnActionPerformed
        AppointmentsUI appointment = new AppointmentsUI();
        appointment.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AppointmentBtnActionPerformed

    private void MedicalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicalBtnActionPerformed
        MedHealthMenuUI medmenu = new MedHealthMenuUI();
        medmenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MedicalBtnActionPerformed

    private void TreatmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TreatmentBtnActionPerformed
        Treatment treatment = new Treatment();
        treatment.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TreatmentBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
   //  AccessRights();
    }//GEN-LAST:event_formWindowOpened

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        LoginUI log = new LoginUI();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutBtnActionPerformed
  //  public void AccessRights(){
       // String AccessLevels = savedData[2];
       // String line;
        //String username = savedData[0];
        
        //try{
         // FileReader fileReader = new FileReader(FILENAME);
         //   BufferedReader bufferRead = new BufferedReader(fileReader);
            
          //while (((line = bufferRead.readLine()) != null)) {
          //    savedData = line.split(","); 
         // if(savedData [0].matches(AccessLevels)){
           //  AccessLevels = savedData[2]; 
          //if(AccessLevels.equals("1")){
          // FinanceBtn.setVisible(false);
          // StaffBtn.setVisible(false);
          // TreatmentBtn.setVisible(false);
          // adminBtn.setVisible(false);   
          //     }  
          //if(AccessLevels.equals("2")){
          // FinanceBtn.setVisible(false); 
          // StaffBtn.setVisible(false);
          // adminBtn.setVisible(false);
           //}
         // if(AccessLevels.equals("3")){
          // AppointmentBtn.setVisible(false);
          // PatientBtn.setVisible(false);
          // TreatmentBtn.setVisible(false);
          // adminBtn.setVisible(false); 
           
          // }
         // if(AccessLevels.equals("4")){
          
          // } 
        
          //}
        
         // } 
        //}catch(Exception e){
        // JOptionPane.showMessageDialog(null,"Error Access Rights");
       // }
    
 
    
 
    public void showDate(){
        Date date = new Date();
        SimpleDateFormat simpledf = new SimpleDateFormat("yyyy-MM-dd");
        DateLbl.setText(simpledf.format(date));
       
    }
    public void showTime(){
        new Timer(0, new ActionListener(){ 
            
            @Override
            public void actionPerformed(ActionEvent e) {
            Date date = new Date();
            SimpleDateFormat simpledf = new SimpleDateFormat("hh:mm:ss a");
            TimeLbl.setText(simpledf.format(date));    
            }
        }).start();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton AppointmentBtn;
    private javax.swing.JLabel DateLbl;
    private javax.swing.JButton LogoutBtn;
    public javax.swing.JButton MedicalBtn;
    public javax.swing.JButton PatientBtn;
    public javax.swing.JButton StaffBtn;
    private javax.swing.JLabel TimeLbl;
    public javax.swing.JButton TreatmentBtn;
    private javax.swing.JLabel UsernameLbl;
    public javax.swing.JToggleButton adminBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
