/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dentalpractice.prototype;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author wakey
 */
public class ProcedureCostUI extends javax.swing.JFrame {
String[] savedData;
String PTFILENAME = "Patients.txt";
String TFILENAME = "Treatment.txt";
    /**
     * Creates new form Treatment
     */
    public ProcedureCostUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LABtn = new javax.swing.JRadioButton();
        RCTBtn = new javax.swing.JRadioButton();
        FillingsBtn = new javax.swing.JRadioButton();
        CrownsBtn = new javax.swing.JRadioButton();
        BridgesBtn = new javax.swing.JRadioButton();
        NOBtn = new javax.swing.JRadioButton();
        RadioGraphsBtn = new javax.swing.JRadioButton();
        ExtractionBtn = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        PatientIDTxt = new javax.swing.JTextField();
        DobTxt = new javax.swing.JTextField();
        AgeTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        CalculateBtn = new javax.swing.JButton();
        CleaningBtn = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        OtherTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        SearchBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        FirstNameTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        DisabilityTxt = new javax.swing.JTextField();
        FinalCostTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Procedure Cost");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Treatment Given");

        LABtn.setText("Local Anesthetic");

        RCTBtn.setText("Root Canal Therapy");

        FillingsBtn.setText("Fillings");

        CrownsBtn.setText("Crowns");

        BridgesBtn.setText("Bridges");

        NOBtn.setText("Nitrous Oxide");

        RadioGraphsBtn.setText("Radiographs");

        ExtractionBtn.setText("Extraction");

        jLabel3.setText("PatientID");

        jLabel4.setText("DOB");

        jLabel5.setText("Age");

        jLabel6.setText("View Patients Medical history Notes/Health Problems");

        jButton1.setText("Medical History");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        PatientIDTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PatientIDTxtKeyReleased(evt);
            }
        });

        DobTxt.setEditable(false);
        DobTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DobTxtActionPerformed(evt);
            }
        });

        AgeTxt.setEditable(false);
        AgeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeTxtActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Final Cost Of Treatment");

        BackBtn.setText("Back");
        BackBtn.setActionCommand("");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        CalculateBtn.setText("Calculate");
        CalculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateBtnActionPerformed(evt);
            }
        });

        CleaningBtn.setText("Cleaning");

        jLabel8.setText("Other");

        jLabel9.setText("Type the cost of other here");

        SearchBtn.setText("Search for Patient");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        jLabel10.setText("FirstName");

        FirstNameTxt.setEditable(false);
        FirstNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FirstNameTxtKeyReleased(evt);
            }
        });

        jLabel11.setText("Disability");

        DisabilityTxt.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel4)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(27, 27, 27)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(FirstNameTxt)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(DobTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(AgeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(DisabilityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(64, 64, 64)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(CleaningBtn)
                                                    .addComponent(jLabel8)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(LABtn)
                                                            .addComponent(BridgesBtn))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(NOBtn)
                                                            .addComponent(RCTBtn)))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(PatientIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(SearchBtn)))
                                        .addGap(0, 6, Short.MAX_VALUE)))))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FillingsBtn)
                            .addComponent(RadioGraphsBtn))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(FinalCostTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(CalculateBtn))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ExtractionBtn)
                                    .addComponent(CrownsBtn))))))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BackBtn)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(OtherTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RCTBtn)
                    .addComponent(FillingsBtn)
                    .addComponent(CrownsBtn)
                    .addComponent(LABtn))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BridgesBtn)
                    .addComponent(NOBtn)
                    .addComponent(RadioGraphsBtn)
                    .addComponent(ExtractionBtn))
                .addGap(18, 18, 18)
                .addComponent(CleaningBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OtherTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PatientIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBtn))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(FirstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(DobTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(AgeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CalculateBtn)
                            .addComponent(FinalCostTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(DisabilityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel6)
                        .addGap(37, 37, 37)
                        .addComponent(jButton1)
                        .addGap(8, 8, 8)
                        .addComponent(BackBtn)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DobTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DobTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DobTxtActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackBtnActionPerformed

    private void CalculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateBtnActionPerformed
     
     int age = Integer.parseInt(AgeTxt.getText());
     String disability = DisabilityTxt.getText();
     double vat = 1.2;
     double finalCost =0;
     
     double LACost = 0;
     double RCTCost = 0;
     double Fillings = 0;
     double Crowns = 0;
     double Bridges = 0;
     double NO = 0;
     double RadioGraphs = 0;
     double Extraction = 0;
     double Cleaning = 0;
     
     if( age < 19){
         finalCost = 0;
     }
     if(disability.equalsIgnoreCase("Yes")){
         finalCost = 0;
     }
     
     if(LABtn.isSelected()){
         LACost = 27.50;
     }else{
         LACost = 0;
     }
     if(FillingsBtn.isSelected()){
         Fillings = 62.10;
     }else{
         Fillings = 0;
     }
     if(RCTBtn.isSelected()){
         RCTCost = 62.10;
     }else{
         RCTCost = 0;
     }
     if(CrownsBtn.isSelected()){
         Crowns = 269.10;
     }else{
         Crowns = 0;
     }
     if(BridgesBtn.isSelected()){
         Bridges = 347.50;
     }else{
         Bridges = 0;
     }
     if(NOBtn.isSelected()){
         NO = 50;
     }else{
         NO = 0;
     }
     if(RadioGraphsBtn.isSelected()){
         RadioGraphs = 101;
     }else{
         RadioGraphs = 0;
     }
     if(ExtractionBtn.isSelected()){
         Extraction = 120;
     }else{
         Extraction = 0;
     }
      if(CleaningBtn.isSelected()){
         Cleaning = 44;
     }else{
         Cleaning = 0;
     }
     Double OtherCost = Double.parseDouble(OtherTxt.getText());
     
     finalCost = LACost + Fillings + RCTCost + Crowns + Bridges + NO + RadioGraphs + Extraction + Cleaning + OtherCost *vat;
     
     FinalCostTxt.setText(String.valueOf("£"+finalCost));
        
    }//GEN-LAST:event_CalculateBtnActionPerformed

    private void PatientIDTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PatientIDTxtKeyReleased
      
      
         
    }//GEN-LAST:event_PatientIDTxtKeyReleased

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
 
                   
    }//GEN-LAST:event_formKeyPressed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
       SearchTable();
       
       int age;
       CalculateAge CalcAge = new CalculateAge();
       String date = DobTxt.getText();
       age = CalcAge.CalcAge(date);
       AgeTxt.setText(String.valueOf(age));
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void FirstNameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FirstNameTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameTxtKeyReleased

    private void AgeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeTxtActionPerformed
       
           
    }//GEN-LAST:event_AgeTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ViewPatientsMedicalHistoryUI vpmc = new ViewPatientsMedicalHistoryUI();
        vpmc.setVisible(true);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
    private void SearchTable(){
        boolean found = false; // boolean flag to indicate if search string found
        String line; // string to temporarily store the line/record read from the file
        try{
        // Create a file reader object 
        FileReader fileReader = new FileReader(PTFILENAME);
        BufferedReader bufferRead = new BufferedReader(fileReader);
        // Loop through file line by line until the end of the file or until we have found it 
            while (((line = bufferRead.readLine()) != null)){
                savedData = line.split(",");                                          
                //check if the record matches
                if(savedData[0].equalsIgnoreCase(PatientIDTxt.getText())){
                    found = true; // set found to true to stop looping 
                }
        }
 
        if (found == true){  
            Details(savedData);//display data in the correct text fields 
            
           
            
        
        }else{
            JOptionPane.showMessageDialog(null, "couldnt find", "Search", JOptionPane.INFORMATION_MESSAGE);
        }
        fileReader.close();  // close file 
        }catch(IOException ex){
            System.err.println("error");
        }
    }
    private void Details(String[] dataArray){ 
    
    FirstNameTxt.setText(dataArray[1]);
    DobTxt.setText(dataArray[5]);
    DisabilityTxt.setText(dataArray[8]);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProcedureCostUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProcedureCostUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProcedureCostUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProcedureCostUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProcedureCostUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgeTxt;
    private javax.swing.JButton BackBtn;
    private javax.swing.JRadioButton BridgesBtn;
    private javax.swing.JButton CalculateBtn;
    private javax.swing.JRadioButton CleaningBtn;
    private javax.swing.JRadioButton CrownsBtn;
    private javax.swing.JTextField DisabilityTxt;
    private javax.swing.JTextField DobTxt;
    private javax.swing.JRadioButton ExtractionBtn;
    private javax.swing.JRadioButton FillingsBtn;
    private javax.swing.JTextField FinalCostTxt;
    private javax.swing.JTextField FirstNameTxt;
    private javax.swing.JRadioButton LABtn;
    private javax.swing.JRadioButton NOBtn;
    private javax.swing.JTextField OtherTxt;
    public javax.swing.JTextField PatientIDTxt;
    private javax.swing.JRadioButton RCTBtn;
    private javax.swing.JRadioButton RadioGraphsBtn;
    private javax.swing.JButton SearchBtn;
    public javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
